/*
Question:

	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


Idea:

	Brute :)
*/

#include <bits/stdc++.h>
using namespace std;

int main()
{
	// Write this Optionally, if you are taking input from file(input.txt) and putting it to a file(output.txt)
	#ifndef ONLINE_JUDGE
	freopen("input.txt","r",stdin);
	freopen("output.txt","w",stdout);
	#endif
	//

	int a=1,b=2;
	int res=0;
	while(b<4000000)
	{
		if((b&1)==0)//Check for the Even
		{
			res+=b;
		}
		int x = a+b;
		a=b;
		b=x;
	}
	cout<<res<<endl;


}